title: Ejemplo Jekyll
email: your-email@example.com
description: >-
  Ejemplo de esqueleto de un sitio web creado con Jekyll 
  para prácticas de alumnos utilizando Markdown, HTML,
  JavaScript, CSS y otras tecnologías relacionadas
baseurl: "/jekyl-skel"
url: "https://carlesvazuqez.github.io/jekyl-skel/"

theme: minima
#plugins:
#  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/

markdown: kramdown
